apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-animals-api
  labels:
    app: mlops-animals-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-animals-api
  template:
    metadata:
      labels:
        app: mlops-animals-api
    spec:
      containers:
      - name: mlops-animals-api
        image: ghcr.io/DaymonPollet/mlops-animals-api:${{ github.sha }} # Image will be tagged with the Git SHA
        ports:
        - containerPort: 80 # Assuming your API listens on port 80 inside the container
        env:
        - name: MODEL_VERSION
          value: "${{ env.MODEL_VERSION_FOR_K8S }}" # Links to the model version downloaded and passed from the workflow
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-animals-api-service
spec:
  selector:
    app: mlops-animals-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Matches the containerPort
  type: LoadBalancer # Exposes the service externally (will get an external IP in cloud K8s)