apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-animals-api
  labels:
    app: mlops-animals-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-animals-api
  template:
    metadata:
      labels:
        app: mlops-animals-api
    spec:
      containers:
      - name: mlops-animals-api
        image: ghcr.io/DaymonPollet/mlops-animals-api:${GITHUB_SHA} # ✅ updated to use envsubst-compatible variable
        ports:
        - containerPort: 8000 # ✅ updated to match Dockerfile
        env:
        - name: MODEL_VERSION
          value: "${MODEL_VERSION_FOR_K8S}" # ✅ envsubst-compatible format
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-animals-api-service
spec:
  selector:
    app: mlops-animals-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 
  type: LoadBalancer
