$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: animals-classification-cli-v4 # <-- NEW NAME! Increment for each submission
display_name: Animals Classification V4 # <-- OPTIONAL: Also update display name
experiment_name: classification

inputs:
  train_test_split_factor: 20
  epochs: 5

outputs:
  model:
    type: uri_folder
    mode: upload
  registration_details:
    type: uri_folder
    mode: upload

settings:
  default_compute: azureml:cli-created-machine

jobs:
  data_prep_pandas:
    type: command
    component: azureml:data_prep_image_resize_cli:0.1.0 # <-- CORRECTED COMPONENT!
    inputs:
      data:
        type: uri_folder
        path: azureml:pandas:1 # Assuming this dataset is registered
    outputs:
      output_data:
        mode: rw_mount

  data_prep_cats:
    type: command
    component: azureml:data_prep_image_resize_cli:0.1.0 # Reference by registered component ID
    inputs:
      data:
        type: uri_folder
        path: azureml:cats:1 # Assuming this dataset is registered
    outputs:
      output_data:
        mode: rw_mount

  data_prep_dogs:
    type: command
    component: azureml:data_prep_image_resize_cli:0.1.0 # Reference by registered component ID
    inputs:
      data:
        type: uri_folder
        path: azureml:dogs:1 # Assuming this dataset is registered
    outputs:
      output_data:
        mode: rw_mount

  data_split:
    type: command
    component: azureml:data_split_cli:0.1.1 # Reference by registered component ID
    inputs:
      animal_1: ${{parent.jobs.data_prep_pandas.outputs.output_data}}
      animal_2: ${{parent.jobs.data_prep_cats.outputs.output_data}}
      animal_3: ${{parent.jobs.data_prep_dogs.outputs.output_data}}
      train_test_split_factor: ${{parent.inputs.train_test_split_factor}}
    outputs:
      testing_data:
        mode: rw_mount
      training_data:
        mode: rw_mount

  training:
    type: command
    component: azureml:training_cli:0.1.0 # Reference by registered component ID
    inputs:
      training_folder: ${{parent.jobs.data_split.outputs.training_data}}
      testing_folder: ${{parent.jobs.data_split.outputs.testing_data}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      output_folder: ${{parent.outputs.model}}

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs:
      model_name: animal-classification
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{ parent.outputs.registration_details }}